// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDyyGyVgxBWifU6GUdVFryoNZ6OryEtkc',
    appId: '1:787546134827:web:1fad0171ae4498b743cd6e',
    messagingSenderId: '787546134827',
    projectId: 'appdev-project-4e1d4',
    authDomain: 'appdev-project-4e1d4.firebaseapp.com',
    storageBucket: 'appdev-project-4e1d4.firebasestorage.app',
    measurementId: 'G-S9GJWTTGJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EhVInMOjAtaAKsZUxYYTuVNFe2Rfxzg',
    appId: '1:787546134827:android:13468d987046694843cd6e',
    messagingSenderId: '787546134827',
    projectId: 'appdev-project-4e1d4',
    storageBucket: 'appdev-project-4e1d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZjco5Q4mcqlEj_O7FxNiGN2WD-rwg8no',
    appId: '1:787546134827:ios:2079e4c6e19961f743cd6e',
    messagingSenderId: '787546134827',
    projectId: 'appdev-project-4e1d4',
    storageBucket: 'appdev-project-4e1d4.firebasestorage.app',
    iosClientId: '787546134827-1iqcvnd170e2f4iei2i0pe679umrlkkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZjco5Q4mcqlEj_O7FxNiGN2WD-rwg8no',
    appId: '1:787546134827:ios:2079e4c6e19961f743cd6e',
    messagingSenderId: '787546134827',
    projectId: 'appdev-project-4e1d4',
    storageBucket: 'appdev-project-4e1d4.firebasestorage.app',
    iosClientId: '787546134827-1iqcvnd170e2f4iei2i0pe679umrlkkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDyyGyVgxBWifU6GUdVFryoNZ6OryEtkc',
    appId: '1:787546134827:web:309c7700ea31f72a43cd6e',
    messagingSenderId: '787546134827',
    projectId: 'appdev-project-4e1d4',
    authDomain: 'appdev-project-4e1d4.firebaseapp.com',
    storageBucket: 'appdev-project-4e1d4.firebasestorage.app',
    measurementId: 'G-37K7BJ2E1W',
  );
}
